### ISSUE TITLE
How to launch a bot

### ISSUE THREAD

**Issue by MrDmitry1107** [RayzrDev/RayzrDevBot#13]
I don`t understand how launch file .json

**Comment by fdsfafsasafsasaasa** [comment]
If you actually mean [package.json](https://docs.npmjs.com/cli/v6/configuring-npm/package-json/) then the docs are a good place to start.

**Comment by CtrlNate** [comment]
The actual start command for the bot is `node src/bot.js`. You don't launch any .json file to run it...

**Comment by MrDmitry1107** [comment]
Ок

**Comment by MrDmitry1107** [comment]
What if I can't use Node.js. Because I use Kali Linux.

**Comment by dehys** [comment]
> 
> 
> What if I can't use Node.js. Because I use Kali Linux.

https://www.youtube.com/watch?v=EGPTXtAXKWc
