### ISSUE TITLE
Rename bot

### ISSUE THREAD

**Issue by foxfirecodes** [RayzrDev/RayzrDevBot#5]
**Please contribute any suggestions you have!**

I'd really like to come up with a new catchy and creative name for the bot. "RayzrDevBot" is just about as uncreative as it gets. Some possible ideas:

##### Fancy
- Aegis
- Vis (a Latin word for power/strength/energy)
- Que

##### Human
- Ben
- Dave
- Gertrude (this one would be funny)
- Jane

##### Tech-y
- Hydro
- Quantum
- Proton
- Atom

Please don't make fun of my name suggestions, this is pure brainstorming/random ideas.

**Comment by Nianor** [comment]
...I like Gertrude. Especially if you can come up with an acronym for it.

**Comment by foxfirecodes** [comment]
Ooooo, yes. Kinda like what I did with [GuRRL](https://github.com/Rayzr522/GuRRL) xD

**Comment by AlexanderBeck0** [comment]
Hydro. Just seems the nicest.

**Comment by ArsenArsen** [comment]
`/bin/init`

**Comment by HeyImSushii** [comment]
I would go with Dave.

**Comment by Votyn** [comment]
@HeyImSushii :musical_note: If I were a stripper :notes: my name would be :musical_note: Dave. :notes: :notes: 
(JackSucksAtLife reference)

**Comment by flfy** [comment]
/dev/null

**Comment by foxfirecodes** [comment]
This is probably irrelevant at this point, as [Rivo](https://github.com/RayzrDev/Rivo) will eventually replace RayzrDev Bot entirely.
